services:
  postgres:
    image: postgres:15
    container_name: web-lab-4-postgres
    restart: always
    environment:
      POSTGRES_DB: weblab3db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
  auth:
    build:
      context: ..
      dockerfile: config/backend/auth/Dockerfile
    networks:
      - backend
    depends_on:
      - postgres
  geometry:
    build:
      context: ..
      dockerfile: config/backend/geometry/Dockerfile
    networks:
      - backend
    depends_on:
      - postgres
#  history:
#    build:
#      context: ..
#      dockerfile: backend/history/Dockerfile
#    depends_on:
#      - postgres
  nginx:
    build: 
      context: ..
      dockerfile: config/nginx/Dockerfile
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      - backend
    depends_on:
      - auth
      - geometry
networks:
  backend:
    driver: bridge